fixtures:
  repositories:
    apache:               'https://github.com/puppetlabs/puppetlabs-apache'
    concat:               'https://github.com/puppetlabs/puppetlabs-concat'
    extlib:               'https://github.com/voxpupuli/puppet-extlib'
    foreman:              'https://github.com/theforeman/puppet-foreman'
    git:                  'https://github.com/theforeman/puppet-git'
    hocon:                'https://github.com/puppetlabs/puppetlabs-hocon'
    inifile:              'https://github.com/puppetlabs/puppetlabs-inifile.git'
    puppet_authorization: 'https://github.com/puppetlabs/puppetlabs-puppet_authorization.git'
    puppetdb:             'https://github.com/puppetlabs/puppetlabs-puppetdb.git'
    stdlib:               'https://github.com/puppetlabs/puppetlabs-stdlib.git'

  symlinks:
    puppet: "#{source_dir}"
